import type { Meta, StoryObj } from '@storybook/vue3';
declare const meta: Meta;
export declare const Primary: Story;
export declare const Success: Story;
export declare const Danger: Story;
export declare const OutlinePrimary: Story;
export declare const OutlineSuccess: Story;
export declare const OutlineDanger: Story;
export declare const Dark: Story;
export declare const OutlineDark: Story;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Small: Story;
export declare const Medium: Story;
export declare const Large: Story;
export declare const Loading: Story;
export declare const Disabled: Story;
export declare const WithLeftIcon: Story;
export declare const WithRightIcon: Story;
